import About from "./About/About"
import Navbar from "./Header/navbar/Navbar"
import Hero from "./Header/hero/Hero"
import Menu from "./Menu/Menu"
import ChefsWord from "./Chef'sWord/ChefsWord"
import Video from "./Video/Video"
import Awards from "./Awards/Awards"
import Gallery from "./Gallery/Gallery"
import Find from "./Find/Find"
import NewsLetter from "./NewsLetter/NewsLetter"
import Footer from "./Footer/Footer"
export {About,Navbar,Hero, Menu, ChefsWord, Video, Awards, Gallery, Find, NewsLetter, Footer}